### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Gokuofuin** [ShioR/EVE-Character-Showroom#65]
Hi there

I get a Internal Server Error 500 when trying to access the install.php in the root.

Thoughts?

**Comment by ShioR** [comment]
Hi,

I'm away from the PC until tomorrow and I'll have a look into it for you.

If you could reply with your software setup that'd be a great help.

Thanks.

**Comment by Gokuofuin** [comment]
My software setup is the Personal Pro package of Arvixe. -> https://www.arvixe.com/linux_web_hosting

**Comment by ShioR** [comment]
Hi,

Apologies for the delay, I've had my fair share of technical issues over the weekend!

I did a test install using the zip from GitHub on a local environment and my live server, both installed without an issue. Except for the .htaccess not being present for me. 

Due to the fact you're getting a 500 error rather than anything else suggests to me that .htaccess is present in your folder structure though.

I also cannot see anything vital that is missing in the Arvixe package, can you get me the version numbers for PHP and MySQL just to confirm these aren't an issue?

Thanks.

**Comment by Gokuofuin** [comment]
Hey there

No worries, I know all about being bugged down with 'bugs' :D haha

Here is the info you asked for:
Apache Version 	2.2.27
PHP Version 	5.4.45
MySQL Version 	5.5.44-37.3

**Comment by ShioR** [comment]
Thanks,

Assuming it's just the install.php that is giving you the error you can actually do a 'manual' install if you feel confident enough.

Basically, all you need to do is add the SQL files into the database manually from `install/sql`, add the database info, domain and change line 43 to be true instead of false in `includes/config.php` and then head over to yourdomain.com/add to add the api details of some characters. :)

**Comment by Gokuofuin** [comment]
Well I have done everything for the manual install but I still get the 404. -> http://charactershowroom.dantecampbell.org/

Any more thoughts on how I can tackle this? ;D

**Comment by ShioR** [comment]
Seems to be working ok for me? Even adding a character works :o

**Comment by Gokuofuin** [comment]
.....sigh.... I'm so stupid sometimes :D lol.... I fixed it by resetting the permissions on FTP.

Thank you for all your help, I would not have been able to manual install without you :D

**Comment by ShioR** [comment]
No worries at all, just glad we managed to get it working for you!
